#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May  3 10:38:51 2020

@author: fabiopaderi
"""

# la virgola è come un paste in R
inp = input('Europe floor?')
usf = int(inp) + 1
print('USA floor is', usf)
if(usf > 4):
    print('You are over 4th')
elif(usf < 4):
    print('You are down 4th')
else:
    print('You are going to the 4th')
    

astr = input("how old are you?:")
try:
    ival = int(astr)
except:
    ival = -1
    
if(ival == -1):
    print("Not a number")
else:
    print('You are', ival, 'years old')

hrs = input("Enter Hours:")
rate = input("Enter Rate:")

try:
    hrs = float(hrs)
    rate = float(rate)
except:
    print("Error in typing hrs or rate")
    quit()

if hrs > 40:
   reg = hrs*rate
   ext = (hrs-40)*(rate*0.5)
   pay = reg+ext
   print("Pay is:", pay)
else:
   pay = reg      
   print("Pay is:", pay)











